https://numpy.org/doc/stable/index.html

**NumPy** offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more. 

**1. Install Numpy package**

In [ ]:
pip install numpy

**2. Import Numpy as np**

In [1]:
import numpy as np

**3. NumPy Array**

In [38]:
# create a list , height.
aa = [1, 4, 9, 16, 30, 36]

In [39]:
# create a numpy array from height: np_height
np_aa = np.array(aa)

In [40]:
# Print out type of np_height
print(type(np_aa))

<class 'numpy.ndarray'>


**4.Calculation**

* NumPy is great for vector arithmetic such as $+$, $-$ , $*$ , $/$ 

In [45]:
np_aa * 3

array([  3,  12,  27,  48,  90, 108])

In [46]:
np_bb = np.array([1,2,3,4,5, 6])

In [47]:
np_cc = np_aa + np_bb

In [48]:
print(type(np_cc))
print(np_cc)

<class 'numpy.ndarray'>
[ 2  6 12 20 35 42]


In [49]:
np_dd = np_aa / np_bb
print(type(np_dd))
print(np_dd)

<class 'numpy.ndarray'>
[1. 2. 3. 4. 6. 6.]


**5. NumPy features**

* Numpy arrays cannot contain elements with different types. 

In [56]:
# create a list , example.
example = [True, 'Hello', 10.11, 100]

print(type(example[0]))
print(type(example[1]))
print(type(example[2]))
print(type(example[3]))

<class 'bool'>
<class 'str'>
<class 'float'>
<class 'int'>


In [51]:
np_example = np.array(example)
print(type(np_example))
print(np_example)

<class 'numpy.ndarray'>
['True' 'Hello' '10.11' '100']


In [57]:
print(np_example[2])
print(type(np_example[2]))

10.11
<class 'numpy.str_'>


In [54]:
np.array([True, 1, 2]) + np.array([0, 0, False])

array([1, 1, 2])

In [59]:
type(np.array([0, 0, False])[2])

numpy.int32

**6.Two dimensions NumPy Array**

In [66]:
# Create 2D NumPy Array
D2 = [[1, 100], [2, 200], [3, 300], [4, 400], [5, 500]]

In [67]:
np_D2 = np.array(D2)

In [68]:
print(type(np_D2))

<class 'numpy.ndarray'>


In [69]:
print(np_D2.shape)

(5, 2)


In [70]:
print(np_D2[0, :])

[  1 100]


In [75]:
print(np_D2[: , 0])

[1 2 3 4 5]


In [80]:
print(np_D2[0:2, 1])

[100 200]


**7.NumPy Statistics**

Practice mean, median, average, correlation

In [81]:
print(np.mean(np_D2[:, 0]))

3.0


In [82]:
print(np.median(np_D2[:,0]))

3.0


In [83]:
# population s.d
print(np.std(np_D2[:,0]))

1.4142135623730951


In [88]:
# sample s.d
print(np.std(np_D2[:,0], ddof=1))

1.5811388300841898


In [87]:
print(np.corrcoef(np_D2[:,0], np_D2[:,1]))

[[1. 1.]
 [1. 1.]]


**4. Create a Numpy by condition**

In [114]:
np_condition = np.array([1,2,3,4,5,6,7,8,9,10])

In [115]:
under_5 = np_condition < 5

In [116]:
print(under_5)

[ True  True  True  True False False False False False False]


In [117]:
under_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [118]:
#or

print(np_condition < 5)

[ True  True  True  True False False False False False False]
